import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ㅌㅏㄷㅏㄱ ターダク",
  description: "Generated by create next app",
  images: [
    {
      url: "/preview.png", // public 폴더 안에 이미지
      width: 1200,
      height: 630,
    },
  ],
  openGraph: {
    title: "ㅌㅏㄷㅏㄱ ターダク",
    description: "한국어/일본어 타자 연습 웹앱",
    images: [
      {
        url: "/preview.png",
        width: 1200,
        height: 630,
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
